services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: taskmanager-app
    environment:
      - DEBUGBAR_ENABLED=false=value
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - taskmanager-network

  db:
    image: postgres:17
    container_name: taskmanager-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskmanager-network

networks:
  taskmanager-network:
    driver: bridge

volumes:
  postgres_data:
  app:
    external: true